/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sns' at '4/29/17 4:33 PM' with Gradle 2.14.1
 *
 * @author sns, @date 4/29/17 4:33 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
